### ISSUE TITLE
error ENOTDIR

### ISSUE THREAD

**Issue by geezer78** [knopkem/dicomweb-proxy#143]
hi Michael,

i'm trying to get your proxy to work, but keep getting an error:
`{"errno":-4052,"code":"ENOTDIR","syscall":"scandir","path":"C:\\DevCode\\dicomweb-proxy\\data\\1.2.276.0.50.5727824.317092924093037266166964141159093409537\\1.2.276.0.50.5727824.198005300577858433457930735998896357809"}`

none of my studies result in thumbnails and images, while the actual dicom files are being retrieved through DIMSE
the example is indeed not a directory, its a dicom file.

if i retry loading the same study i see that it actually goes further and sees its a file, then returns the file as a buffer but then the viewer in the browser errors out..
```
index.worker.e62ecca63f1a2e124230.worker.js:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at index.worker.e62ecca63f1a2e124230.worker.js:1:141462
    at R (index.worker.e62ecca63f1a2e124230.worker.js:1:143127)
    at async Object.handler (index.worker.e62ecca63f1a2e124230.worker.js:1:143400)
```

i have two questions:

1. In the case that the study needs to be retrieved through DIMSE, should the ohif viewer auto update the view?
2. do you have any thoughts about these errors?

edit:
i have narrowed it down to wadRs.ts where the error occurs on the proxy server side.

after reload the study is actually present and no error occurs on the proxy side. however the viewer errors on processing the pixeldata because it is undefined:
![image](https://github.com/knopkem/dicomweb-proxy/assets/7503874/48b837e8-ebae-4c17-a18e-9911d0608337)

i have also built a new version of the ohif viewer from the actual release 3.70 version and replaced the beta version with that but that did not change anything.

**Comment by knopkem** [comment]
hi,
apart from adding a new peer AET, what other configs from the default did you change? (e.g. do you use another transfer syntax or c-move rather c-get).
The OHIF viewer should be already 3.7.0 release and not beta anymore if you are on master branch.
I will try to reproduce it, but probably not the next week (vacation)

**Comment by geezer78** [comment]
i actually was not on master but checkedout the tag1.10.2 for some reason... after switching to master it just works... ;-)

i will experiment further, but for now, enjoy the holiday and thanks for the fast response

**Comment by jmhmd** [comment]
Hi, I have been testing this on macos, and am also seeing intermittent ENOTDIR errors when fetching instances from a local Horos DIMSE server. I am on the latest master branch. I have managed to fix this by ensuring the instance exists on disk after the DIMSE fetch request promise resolves:

in `fileHelper.ts` added this function:
```ts
export async function waitForFile(pathname: string, maxRetries = 3, delay = 100) {
  let lastError: any;
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      if (await fileExists(pathname)) {
        return true;
      } else {
        throw new Error(`file not found: ${pathname}`);
      }
    } catch (error) {
      lastError = error;
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }
  throw lastError;
}
```
and then in `wadoRs.ts` added an awaited check after fetching:
```ts
if (!useCache) {
    // We're not using the cache, so go and fetch the files. This will happen even if just one file is missing.
    // Could this be improved to just get the needed files?
    logger.info(`fetching ${pathname}`);
    await waitOrFetchData(studyInstanceUid, seriesInstanceUid ?? '', sopInstanceUid ?? '', queryLevel).then();

    // Check if the file exists now
    const fileOnDisk = await waitForFile(pathname);
    if (fileOnDisk) {
      isDir = false;
    }
  }
```

My best guess is this may be os-specific differences in how DIMSE + the filesystem settles the fetched data with regards to when the DIMSE request concludes.

I am new to this library, but can submit a pull request if you agree. BTW, this library looks great!

**Comment by knopkem** [comment]
Reopening issue as it seems still be present.

**Comment by knopkem** [comment]
@jmhmd Your changes look good to me, you can go ahead with creating a PR if you like. Thanks. I guess, the scu returns without waiting for the file to be written to disk, so in most cases (and depending on hardware) it will work but sometimes not, your change should handle it.
