### ISSUE TITLE
Error: Configuration property "useKeycloakAuth" is not defined

### ISSUE THREAD

**Issue by Pablohn26** [knopkem/dicomweb-proxy#73]
I am getting the following error when trying to run the app by default:

```
dicomweb-proxy_1  | stderr: /app/node_modules/config/lib/config.js:182
dicomweb-proxy_1  |     throw new Error('Configuration property "' + property + '" is not defined');
dicomweb-proxy_1  |     ^
dicomweb-proxy_1  | 
dicomweb-proxy_1  | Error: Configuration property "useKeycloakAuth" is not defined
dicomweb-proxy_1  |     at Config.get (/app/node_modules/config/lib/config.js:182:11)
dicomweb-proxy_1  |     at Object.<anonymous> (/app/node_modules/dicomweb-proxy/src/app.js:20:12)
dicomweb-proxy_1  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
dicomweb-proxy_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
dicomweb-proxy_1  |     at Module.load (internal/modules/cjs/loader.js:863:32)
dicomweb-proxy_1  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
dicomweb-proxy_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
dicomweb-proxy_1  |     at internal/main/run_main_module.js:17:47
dicomweb-proxy_1  | 
dicomweb-proxy_1  | child process exited with code 1

```

Adding the following line I can skip the error

> config.useKeycloakAuth = false;

**Comment by Pablohn26** [comment]
same problem with:

```
dicomweb-proxy_1  | stderr: (node:20) UnhandledPromiseRejectionWarning: Error: Configuration property "clearCacheOnStartup" is not defined

```

Adding the following line I can skip the error
> config.clearCacheOnStartup = true;

**Comment by knopkem** [comment]
Hi,
this is weird, both of these settings have been used in the past, but they are not used in the current code. Also I just tested both ways of running the proxy (npm and git branch) and both have no problem running.
How did you run this? It looks like some weird mixup with older code.
